/**
 * `assets` collection - PRD Section 15.
 *
 * SYNTHETIC, except where noted. Physical assets generated by T4 against real
 * corridor sections. Two criticality inputs are genuinely real and must never
 * be treated as generated: `trainsAffectedCount` (trains T3 observed on the
 * section) and `passengerDependency` (premium share of the real class mix).
 *
 * `synthetic` is stored per record on purpose - PRD Section 5's real/simulated
 * boundary has to survive into the database and onto the screen, not stop at
 * the JSON file (docs/DECISIONS.md D-015).
 */
import mongoose from 'mongoose';

const degradationPointSchema = new mongoose.Schema(
  {
    date: { type: String, required: true },
    healthMetric: { type: Number, required: true },
  },
  { _id: false },
);

const assetSchema = new mongoose.Schema(
  {
    _id: { type: String, required: true },
    corridorId: { type: String, required: true, index: true },
    assetType: { type: String, enum: ['track', 'signal', 'OHE'], required: true },
    department: {
      type: String,
      enum: ['Engineering', 'S&T', 'TRD'],
      required: true,
      index: true,
    },

    criticality: {
      // REAL - premium share of the observed train class mix (T3).
      passengerDependency: { type: Number, required: true },
      alternateRouteAvailable: { type: Boolean, required: true },
      safetyImportance: { type: Number, required: true },
      historicalFailureFreq: { type: Number, required: true },
      // REAL - trains observed on the section (T3).
      trainsAffectedCount: { type: Number, required: true },
    },

    // FR2.1 weighted score, 0-100.
    criticalityScore: { type: Number, required: true, index: true },
    // FR2.4 requires showing WHICH factor dominated, so the normalised
    // component breakdown ships with the asset rather than being recomputed.
    criticalityBreakdown: { type: Map, of: Number, default: {} },
    dominantCriticalityFactor: { type: String, default: null },

    // SIMULATED asset-health series (PRD 9.1). Not observed Indian Railways
    // data - designed to be replaced by real historical asset-health data.
    degradationHistory: { type: [degradationPointSchema], default: [] },

    synthetic: { type: Boolean, default: true },
  },
  { versionKey: false, _id: false },
);

export const Asset = mongoose.model('Asset', assetSchema, 'assets');
export default Asset;
