/**
 * `assets` collection - PRD Section 15.
 *
 * SYNTHETIC, except where noted. Physical assets generated by T4 against real
 * corridor sections. Two criticality inputs are genuinely real and must never
 * be treated as generated: `trainsAffectedCount` (trains T3 observed on the
 * section) and `passengerDependency` (premium share of the real class mix).
 *
 * `synthetic` is stored per record on purpose - PRD Section 5's real/simulated
 * boundary has to survive into the database and onto the screen, not stop at
 * the JSON file (docs/DECISIONS.md D-015).
 */
import mongoose, { Schema, type HydratedDocument, type Model } from 'mongoose';

export type Department = 'Engineering' | 'S&T' | 'TRD';
export type AssetType = 'track' | 'signal' | 'OHE';

export interface DegradationPoint {
  date: string;
  healthMetric: number;
}

export interface AssetCriticality {
  /** REAL - premium share of the observed train class mix (T3). */
  passengerDependency: number;
  alternateRouteAvailable: boolean;
  safetyImportance: number;
  historicalFailureFreq: number;
  /** REAL - trains observed on the section (T3). */
  trainsAffectedCount: number;
}

export interface IAsset {
  _id: string;
  corridorId: string;
  assetType: AssetType;
  department: Department;
  criticality: AssetCriticality;
  /** FR2.1 weighted score, 0-100. */
  criticalityScore: number;
  /** FR2.4 - which factor dominated, shipped rather than recomputed. */
  criticalityBreakdown: Map<string, number>;
  dominantCriticalityFactor: string | null;
  /** SIMULATED asset-health series (PRD 9.1). Not observed IR data. */
  degradationHistory: DegradationPoint[];
  /**
   * FR2.2 predictive failure risk, 0-100 (T16). Null when the model could not
   * assess the asset - `failureRiskReason` says why. Never defaulted: a missing
   * measurement must not read as a low-risk finding.
   */
  failureRiskScore: number | null;
  failureRiskBreakdown: Record<string, unknown> | null;
  failureRiskComputed: boolean;
  failureRiskReason: string | null;
  /** PRD 9.1 framing. Stored WITH the score so the two cannot be separated. */
  failureRiskFraming: string | null;
  failureRiskComputedAt: Date | null;
  synthetic: boolean;
}

export type AssetDocument = HydratedDocument<IAsset>;

const degradationPointSchema = new Schema<DegradationPoint>(
  {
    date: { type: String, required: true },
    healthMetric: { type: Number, required: true },
  },
  { _id: false },
);

const assetSchema = new Schema<IAsset>(
  {
    _id: { type: String, required: true },
    corridorId: { type: String, required: true, index: true },
    assetType: { type: String, enum: ['track', 'signal', 'OHE'], required: true },
    department: {
      type: String,
      enum: ['Engineering', 'S&T', 'TRD'],
      required: true,
      index: true,
    },

    criticality: {
      passengerDependency: { type: Number, required: true },
      alternateRouteAvailable: { type: Boolean, required: true },
      safetyImportance: { type: Number, required: true },
      historicalFailureFreq: { type: Number, required: true },
      trainsAffectedCount: { type: Number, required: true },
    },

    criticalityScore: { type: Number, required: true, index: true },
    criticalityBreakdown: { type: Map, of: Number, default: {} },
    dominantCriticalityFactor: { type: String, default: null },
    degradationHistory: { type: [degradationPointSchema], default: [] },
    failureRiskScore: { type: Number, default: null },
    failureRiskBreakdown: { type: Schema.Types.Mixed, default: null },
    failureRiskComputed: { type: Boolean, default: false },
    failureRiskReason: { type: String, default: null },
    failureRiskFraming: { type: String, default: null },
    failureRiskComputedAt: { type: Date, default: null },
    synthetic: { type: Boolean, default: true },
  },
  { versionKey: false, _id: false },
);

export const Asset: Model<IAsset> = mongoose.model<IAsset>('Asset', assetSchema, 'assets');
export default Asset;
