/**
 * `tasks` collection - PRD Section 15.
 *
 * SYNTHETIC. The maintenance/defect backlog generated by T4 (PRD 5.2).
 *
 * `priorityScore` and `failureRiskScore` are null until T7 (FR2.3) and T16
 * (FR2.2) compute them. Null means "not yet scored" and must never be read as
 * zero - a task with no score has not been ranked, it is not unimportant.
 */
import mongoose from 'mongoose';

const taskSchema = new mongoose.Schema(
  {
    _id: { type: String, required: true },
    department: {
      type: String,
      enum: ['Engineering', 'S&T', 'TRD'],
      required: true,
      index: true,
    },
    corridorId: { type: String, required: true, index: true },
    assetId: { type: String, required: true, index: true },
    defectType: { type: String, required: true },
    severity: { type: Number, min: 1, max: 5, required: true, index: true },

    // Stored as ISO date strings, matching the generator output exactly rather
    // than being coerced to Date - the round-trip stays byte-comparable against
    // data/processed/tasks.json, which is what the seed sanity check relies on.
    dateRaised: { type: String, required: true },
    slaDueDate: { type: String, required: true },

    estBlockDurationMins: { type: Number, required: true },

    requiredResourceId: { type: String, default: null, index: true },
    // Extension beyond the PRD's singular field: PRD 5.2 describes a task
    // needing a crew AND a machine AND a permission (9.8, T25).
    requiredResourceIds: { type: [String], default: [] },

    dependsOnTaskId: { type: String, default: null, index: true },
    workflowStage: { type: String, default: null },

    // Populated downstream - never guessed at seed time. The seed always
    // writes null; T10's orchestration fills priorityScore from the FR2.3
    // engine, and T16 will fill failureRiskScore.
    priorityScore: { type: Number, default: null },
    failureRiskScore: { type: Number, default: null },

    // FR2.4 requires the ranked queue to show WHICH factor dominated, so the
    // breakdown is stored alongside the score rather than being recomputed -
    // the same choice T4 made with the asset criticalityBreakdown.
    priorityBreakdown: { type: mongoose.Schema.Types.Mixed, default: null },
    dominantPriorityFactor: { type: String, default: null },
    priorityComputedAt: { type: Date, default: null },

    status: {
      type: String,
      enum: ['pending', 'scheduled', 'deferred'],
      default: 'pending',
      index: true,
    },
    synthetic: { type: Boolean, default: true },
  },
  { versionKey: false, _id: false },
);

taskSchema.index({ corridorId: 1, department: 1 });

export const Task = mongoose.model('Task', taskSchema, 'tasks');
export default Task;
