/**
 * `tasks` collection - PRD Section 15.
 *
 * SYNTHETIC. The maintenance/defect backlog generated by T4 (PRD 5.2).
 *
 * `failureRiskScore` is null until T16 computes it. Null means "not yet
 * scored" and must never be read as zero - a task with no score has not been
 * ranked, it is not unimportant.
 */
import mongoose, { Schema, type HydratedDocument, type Model } from 'mongoose';
import type { Department } from './Asset.js';

export type TaskStatus = 'pending' | 'scheduled' | 'deferred';

/** FR2.4 - the per-factor reasoning behind `priorityScore`. */
export interface PriorityBreakdown {
  components: Record<string, number>;
  contributions: Record<string, number>;
  daysToDue: number;
  isOverdue: boolean;
  /** False until T16 exists; the flag travels so nobody assumes otherwise. */
  usesFailureRisk: boolean;
}

export interface ITask {
  _id: string;
  department: Department;
  corridorId: string;
  assetId: string;
  defectType: string;
  severity: number;

  // Stored as ISO date strings, matching the generator output exactly rather
  // than being coerced to Date - the round-trip stays byte-comparable against
  // data/processed/tasks.json, which is what the seed sanity check relies on.
  dateRaised: string;
  slaDueDate: string;

  estBlockDurationMins: number;

  requiredResourceId: string | null;
  /** Extension beyond the PRD's singular field (PRD 5.2 / 9.8, T25). */
  requiredResourceIds: string[];

  dependsOnTaskId: string | null;
  workflowStage: string | null;

  /**
   * The dept_engineer account that submitted this request via FR1.1's
   * submission form (auth session). `null` for every seed-generated task -
   * the synthetic 89-task backlog was never "raised by" any account, and null
   * must stay null rather than being backfilled to a guess.
   */
  raisedByUserId: string | null;

  /** Written by T10's orchestration from the FR2.3 engine. */
  priorityScore: number | null;
  /** Null until T16 (FR2.2 / PRD 9.1). */
  failureRiskScore: number | null;
  priorityBreakdown: PriorityBreakdown | null;
  dominantPriorityFactor: string | null;
  priorityComputedAt: Date | null;

  status: TaskStatus;
  synthetic: boolean;
}

export type TaskDocument = HydratedDocument<ITask>;

const taskSchema = new Schema<ITask>(
  {
    _id: { type: String, required: true },
    department: {
      type: String,
      enum: ['Engineering', 'S&T', 'TRD'],
      required: true,
      index: true,
    },
    corridorId: { type: String, required: true, index: true },
    assetId: { type: String, required: true, index: true },
    defectType: { type: String, required: true },
    severity: { type: Number, min: 1, max: 5, required: true, index: true },

    dateRaised: { type: String, required: true },
    slaDueDate: { type: String, required: true },

    estBlockDurationMins: { type: Number, required: true },

    requiredResourceId: { type: String, default: null, index: true },
    requiredResourceIds: { type: [String], default: [] },

    dependsOnTaskId: { type: String, default: null, index: true },
    workflowStage: { type: String, default: null },

    raisedByUserId: { type: String, default: null, index: true },

    // The seed always writes null; T10's orchestration fills priorityScore
    // from the FR2.3 engine, and T16 will fill failureRiskScore.
    priorityScore: { type: Number, default: null },
    failureRiskScore: { type: Number, default: null },

    // FR2.4 requires the ranked queue to show WHICH factor dominated, so the
    // breakdown is stored alongside the score rather than being recomputed -
    // the same choice T4 made with the asset criticalityBreakdown.
    priorityBreakdown: { type: Schema.Types.Mixed, default: null },
    dominantPriorityFactor: { type: String, default: null },
    priorityComputedAt: { type: Date, default: null },

    status: {
      type: String,
      enum: ['pending', 'scheduled', 'deferred'],
      default: 'pending',
      index: true,
    },
    synthetic: { type: Boolean, default: true },
  },
  { versionKey: false, _id: false },
);

taskSchema.index({ corridorId: 1, department: 1 });

export const Task: Model<ITask> = mongoose.model<ITask>('Task', taskSchema, 'tasks');
export default Task;
