/**
 * Display logic for the FR6.1 approval workflow and the FR6.2 audit trail.
 *
 * Pure, and separate from the components for the reason established in T14 and
 * T18: what a Controller is TOLD about a plan's state is a correctness
 * question, and correctness questions get tests. Rendering does not.
 *
 * The state machine itself lives on the server (`approvalEngine.ts`) and is not
 * duplicated here. This module never decides what is legal - it reads
 * `allowedActions` off the API response and turns it into labels. A second
 * transition table in the browser would be a second thing to drift, and the one
 * that drifts is always the one that offers a button the server refuses.
 */
import type { ScheduleOverride } from '../api/apiSlice.ts'

export type WorkflowState = 'draft' | 'under_review' | 'approved' | 'rejected' | 'published'
export type WorkflowAction = 'submit' | 'approve' | 'reject' | 'publish'

export interface PlanCheck {
  check: string
  passed: boolean
  detail: string
}

export interface ScheduleApproval {
  _id: string
  scheduleId: string
  action: WorkflowAction
  fromState: WorkflowState
  toState: WorkflowState
  reason: string
  actorRole: string
  validation: {
    constraintsSatisfied: boolean
    checks: PlanCheck[]
    knownUnresolved: Array<{ type: string; count: number }>
  } | null
  version: number | null
  publishedPlanDigest: string | null
  createdAt: string
}

export type AuditEntry =
  | { kind: 'generated'; at: string; detail: Record<string, unknown> }
  | { kind: 'override'; at: string; detail: ScheduleOverride }
  | { kind: 'approval'; at: string; detail: ScheduleApproval }

export interface AuditTrail {
  scheduleId: string
  state: WorkflowState
  allowedActions: WorkflowAction[]
  overridable: boolean
  version: number | null
  publishedAt: string | null
  /** Null when never published; false means the plan drifted after issue. */
  digestMatchesPublished: boolean | null
  entries: AuditEntry[]
}

/* -------------------------------------------------------------------------- */

export interface StateDescription {
  label: string
  /** What this state MEANS operationally, not a restatement of the label. */
  meaning: string
  tone: 'neutral' | 'progress' | 'good' | 'bad'
}

const STATES: Record<WorkflowState, StateDescription> = {
  draft: {
    label: 'Draft',
    meaning: 'Generated by the optimizer. Nobody has reviewed it.',
    tone: 'neutral',
  },
  under_review: {
    label: 'Under review',
    meaning: 'With a Controller. Can still be amended.',
    tone: 'progress',
  },
  approved: {
    label: 'Approved',
    meaning: 'Signed off and re-validated. Not yet issued.',
    tone: 'good',
  },
  rejected: {
    label: 'Rejected',
    meaning: 'Will not be issued. Generate a new plan.',
    tone: 'bad',
  },
  published: {
    label: 'Published',
    meaning: 'Issued to crews and frozen. Amendments need a new plan.',
    tone: 'good',
  },
}

/**
 * States in which the server still accepts an FR6.2 override.
 *
 * Mirrors `approvalEngine.ts`, and is the ONE thing this module duplicates from
 * the server - deliberately, because it decides whether an affordance is even
 * offered, and a click that starts a flow the server then refuses reads as the
 * system being broken rather than as the plan being closed. Kept honest by the
 * fact that `allowedActions` (which does come from the server) goes empty in
 * exactly the same two states.
 */
export const OVERRIDABLE_STATES: ReadonlySet<WorkflowState> = new Set([
  'draft',
  'under_review',
  'approved',
])

export function describeState(state: WorkflowState): StateDescription {
  return STATES[state] ?? { label: state, meaning: '', tone: 'neutral' }
}

export interface ActionDescription {
  label: string
  /** FR6.2's reasoning requirement, applied to rejection (D-057). */
  requiresReason: boolean
  /** Actions that cannot be walked back get a confirmation, not a click. */
  terminal: boolean
}

const ACTIONS: Record<WorkflowAction, ActionDescription> = {
  submit: { label: 'Send for review', requiresReason: false, terminal: false },
  approve: { label: 'Approve', requiresReason: false, terminal: false },
  reject: { label: 'Reject', requiresReason: true, terminal: true },
  publish: { label: 'Publish', requiresReason: false, terminal: true },
}

export function describeAction(action: WorkflowAction): ActionDescription {
  return ACTIONS[action] ?? { label: action, requiresReason: false, terminal: false }
}

/**
 * Is this action ready to submit?
 *
 * Only ever a REASON check. Whether the transition is legal at all was decided
 * by the server and arrives as `allowedActions`; re-deciding it here is how a
 * UI ends up disagreeing with its own API.
 */
export function canSubmitAction(action: WorkflowAction, reason: string): boolean {
  return !describeAction(action).requiresReason || reason.trim().length >= 8
}

/**
 * The plain-English answer to "who approved this?".
 *
 * The not-yet-approved case is the one that matters. A UI that showed nothing
 * until a plan was approved would let a Controller read an unreviewed plan as
 * an approved one, which is the same failure the explanation layer guards
 * against with its own workflow fact - and the honest answer is a STATE, not a
 * blank. Attribution is by ROLE: this prototype has no user accounts, so there
 * is no person to name and the copy must not imply one.
 */
export function describeSignOff(trail: Pick<AuditTrail, 'state' | 'version' | 'entries'>): string {
  const approval = trail.entries
    .filter((entry): entry is Extract<AuditEntry, { kind: 'approval' }> => entry.kind === 'approval')
    .reverse()
    .find((entry) => entry.detail.action === 'approve')

  if (!approval) {
    return trail.state === 'rejected'
      ? 'Nobody approved this plan — it was rejected.'
      : 'Not approved yet. No sign-off has been recorded against this plan.'
  }

  const when = new Date(approval.detail.createdAt).toLocaleString()
  const published = trail.version !== null ? ` Published as version ${trail.version}.` : ''
  return `Approved by the ${approval.detail.actorRole} role on ${when}.${published}`
}

/**
 * What the FR6.2 trail says happened, as one line per entry.
 *
 * Kept here rather than in JSX so the wording is testable: an audit trail whose
 * summary is subtly wrong is worse than none, because it is read instead of the
 * record it summarises.
 */
export function summariseEntry(entry: AuditEntry): string {
  if (entry.kind === 'generated') {
    const by = (entry.detail.generatedBy as string) ?? 'the optimizer'
    return `Plan generated by ${by}`
  }
  if (entry.kind === 'override') {
    const override = entry.detail
    return override.action === 'defer'
      ? `${override.taskId} deferred by the ${override.actorRole} role`
      : `${override.taskId} moved to ${override.newAssignment?.date ?? '?'} ` +
          `${override.newAssignment?.start ?? ''} by the ${override.actorRole} role`
  }
  const approval = entry.detail
  const version = approval.version !== null ? ` as version ${approval.version}` : ''
  return `Plan ${approval.toState.replace('_', ' ')}${version} by the ${approval.actorRole} role`
}

/**
 * A warning to show when a published plan no longer replays to what was issued.
 *
 * Null in both healthy cases - never published, or published and matching -
 * because a banner that appears when nothing is wrong is a banner nobody reads.
 */
export function publicationDriftWarning(trail: Pick<AuditTrail, 'digestMatchesPublished'>): string | null {
  if (trail.digestMatchesPublished !== false) return null
  return (
    'This published plan no longer matches the version that was issued. Its records were ' +
    'changed outside the approval workflow — treat the audit trail below as authoritative ' +
    'and re-issue before any work is carried out.'
  )
}
